### ISSUE TITLE
hazard deaggregation for some imts (SA4P0 and SA5P0) not working

### ISSUE THREAD

**Issue by nassermarafi** [usgs/nshmp-haz#157]
I noticed that the hazard deaggregation does not currently work for imts. The error message is below:

The error occurs for both the 2008 and 2014 maps.

DeaggCalc: error
 Arguments: [../../../../nshmp-model-cous-2014/Western US, sites.geojson, 2475, config.json]

com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Gmm: AB_03_GLOB_INTER does not support Imt: SA4P0
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2207)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4881)
        at org.opensha2.gmm.Gmm.instance(Gmm.java:545)
        at org.opensha2.gmm.Gmm.instances(Gmm.java:559)
        at org.opensha2.gmm.Gmm.instances(Gmm.java:576)
        at org.opensha2.calc.Transforms$SourceToCurves.<init>(Transforms.java:303)
        at org.opensha2.calc.CalcFactory.sourcesToCurves(CalcFactory.java:62)
        at org.opensha2.calc.Calcs.asyncHazardCurve(Calcs.java:178)
        at org.opensha2.calc.Calcs.hazard(Calcs.java:136)
        at org.opensha2.HazardCalc.calc(HazardCalc.java:226)
        at org.opensha2.DeaggCalc.calc(DeaggCalc.java:154)
        at org.opensha2.DeaggCalc.run(DeaggCalc.java:104)
        at org.opensha2.DeaggCalc.main(DeaggCalc.java:62)
Caused by: java.lang.IllegalArgumentException: Gmm: AB_03_GLOB_INTER does not support Imt: SA4P0
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:146)
        at org.opensha2.gmm.Gmm.createInstance(Gmm.java:528)
        at org.opensha2.gmm.Gmm.access$000(Gmm.java:46)
        at org.opensha2.gmm.Gmm$1.load(Gmm.java:522)
        at org.opensha2.gmm.Gmm$1.load(Gmm.java:519)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3542)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2323)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2286)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
        ... 15 more

Thanks,

**Comment by emthompson-usgs** [comment]
This is because the maximum period of the AB03 GMPE is 3 sec. You can see this in Table 1 of the paper and also the coefficient table in the nshmp-haz code [here](https://github.com/usgs/nshmp-haz/blob/master/src/org/opensha2/gmm/coeffs/AB03_cascadia_interface.csv).

**Comment by nassermarafi** [comment]
Thanks for your response. I noticed that the hazard deaggregation on the USGS website goes past 3s? Do you know what the code is doing there?

**Comment by pmpowers-usgs** [comment]
You'll note in the text report of the online tool of a 5s deagg for Seattle that AB_03 is absent. Because it doesn't support that period it is dropped from consideration; I assume it's weight is correctly redistributed to the other two interface models. I'm not sure we'll support this type of behavior moving forward.

**Comment by pmpowers-usgs** [comment]
The error checking for this could perhaps be improved by checking first whether the period of interest is supported by all GMMs in the model being used. That said, the forth line of the submitted error message does state the problem.
