### ISSUE TITLE
Coastal Cascadia sites failing

### ISSUE THREAD

**Issue by pmpowers-usgs** [usgs/nshmp-haz#90]
Sites directly over the hanging wall of cascadia ruptures fail with:

HazardCalc: error
 Arguments: [../nshmp-model-cous-2014_3periods/Western US/, unit_tests_3periods/config-sites-test.json]

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: to be removed
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at org.opensha2.programs.HazardCalc.calc(HazardCalc.java:225)
	at org.opensha2.programs.HazardCalc.calc(HazardCalc.java:172)
	at org.opensha2.programs.HazardCalc.run(HazardCalc.java:131)
	at org.opensha2.programs.HazardCalc.main(HazardCalc.java:82)
Caused by: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException: to be removed
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:476)
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:455)
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:79)
	at org.opensha2.calc.CalcFactory.toHazardResult(CalcFactory.java:165)
	at org.opensha2.calc.Calcs.asyncHazardCurve(Calcs.java:190)
	at org.opensha2.calc.Calcs.hazardCurve(Calcs.java:135)
	at org.opensha2.programs.HazardCalc.calc(HazardCalc.java:221)
	... 3 more
Caused by: java.lang.UnsupportedOperationException: to be removed
	at org.opensha2.eq.fault.surface.AbstractGriddedSurface.getEvenlyDiscritizedPerimeter(AbstractGriddedSurface.java:114)
	at org.opensha2.eq.fault.surface.AbstractGriddedSurface.getPerimeter(AbstractGriddedSurface.java:123)
	at org.opensha2.eq.model.Distance.compute(Distance.java:141)
	at org.opensha2.eq.fault.surface.AbstractGriddedSurface.distanceTo(AbstractGriddedSurface.java:149)
	at org.opensha2.calc.Transforms$SourceToInputs.apply(Transforms.java:84)
	at org.opensha2.calc.Transforms$SourceToInputs.apply(Transforms.java:69)
	at org.opensha2.calc.Transforms$SourceToCurves.apply(Transforms.java:322)
	at org.opensha2.calc.Transforms$SourceToCurves.apply(Transforms.java:296)
	at com.google.common.util.concurrent.Futures$ChainingFuture.doTransform(Futures.java:1464)
	at com.google.common.util.concurrent.Futures$ChainingFuture.doTransform(Futures.java:1453)
	at com.google.common.util.concurrent.Futures$AbstractChainingFuture.run(Futures.java:1408)
	at com.google.common.util.concurrent.Futures$2$1.run(Futures.java:1177)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Reported by @ashumway-usgs

**Comment by pmpowers-usgs** [comment]
Some time ago, the getPerimiter() methods of gridded surface were deprecated and set to throw UnsupportedOperationExceptions in advance of cleaning up or removing them. In Cascadia, where the default surface spacing is ~5km, coastal sites can easily end up being tested as being 'continued' by the border of a rupture. I Think we're just getting lucky everywhere else in the WUS where surface saying is 1km and rJB always just happen to be greater.

The methods are obviously needed and should be implemented as RuptureSurface.border().contains(loc) or similar. The border itself should probably be created lazily but cached after creation, although aggressive creation will likely have little impact.
